Creating a data model
dazehinn/BlogApp pull request #1
Opened 2023-07-18 22:42 UTC by dazehinn

### Features in this PR
* Created new rails app
* Built project schema 
* Created and ran necessary migration files

2023-07-18 23:06 UTC, Reem-lab reviewed
Hi @dazehinn, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a live demo section in your README but Microversse announced that you should delete the live demo section since you didn't deploy the project and it is not required to deploy, but you can add it once you deploy it
so for now just I am asking to delete the live demo section 🚀💯💯


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-19 13:00 UTC, DammyShittu requested changes
Hi @dazehinn,

## Highlights
✔️ Schema tables

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 13:00 UTC, DammyShittu commented on config/database.yml
> +  database: db/production.sqlite3
- [ ] Your database should be configured to use PostgreSQL, instead of sqlite. Kindly fix this.

2023-07-19 18:50 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @dazehinn 👋, 

Great job implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

## Highlights 🎯 
✔️ Migration files to set up database tables created 📌 
✔️ Good commit history
✔️ No linter errors

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 19:02 UTC, merged