Views
dazehinn/BlogApp pull request #6
Opened 2023-07-28 15:24 UTC by dazehinn

Update views to match the wireframe design

2023-07-28 18:07 UTC, TadesseDev requested changes
### Hi @dazehinn 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
 - [ ] All linter passed 👍 
## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
- [Optional] Please try to be more descriptive in your pull request sumery. This is a place where you can introduce what changes you have made since the last merge. You can also specify any information that you would like to communicate with the code reviewer of the project.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 18:07 UTC, TadesseDev commented on app/controllers/users_controller.rb
> +
- [ ] Dear @dazehinn, according to the requirement It's required the users_controller `#index` action renders all users to their corresponding Views index page `(app/views/users/index.html.erb)`, currently you have an empty `index action`. Please fetch all users here.

2023-07-28 18:07 UTC, TadesseDev commented on app/controllers/users_controller.rb
> +  def show; end
- [ ] Also in the `app/views/users/show.html.erb` I notice you have used `user.last_posts.each` but in the corresponding controller action `users_controller` of `#show` action you have not declared this instance, Please initialize the instance before using it.

2023-07-28 18:07 UTC, TadesseDev commented on app/views/users/index.html.erb
> +        <% end %>
- [ ] Dear @dazehinn, You did well displaying the `user.name` and `user.posts_counter` of the user, But as the requirement mentioned we need to display the `user.photo` alongside these details. Please add a display for the user photo.
- [Optional] Consider using partials to render the user. create a file in `app/views/users/_user.html.erb` and add the details for displaying a single user in there, once that is done you can reuse this partial for displaying the user details.

2023-07-28 18:07 UTC, TadesseDev commented on app/views/posts/index.html.erb
> +  </section>
- [ ] Dear @dazehinn, It's my belief there was a manual change to the migration file, This caused an issue while I try to migrate the project and start it. As you can see there is a migration pending but could not migrate the project. This prevents me from checking the project locally. Please make sure its possible to drop and migrate your project before the next review request. 
### The error on the console. 
![image](https://github.com/dazehinn/BlogApp/assets/69077061/b6123950-cc03-4201-807a-16a0305ae5b2)
### On the browser
![image](https://github.com/dazehinn/BlogApp/assets/69077061/caaff447-92cc-4933-9491-eaa065121d66)

2023-07-29 20:07 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @dazehinn, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  Great job. Your app works as expected. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 22:01 UTC, merged